---
name: "WCAG 2.2 AA "
on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: read-all

jobs:
  test_accessibility:
    name: Test Accessibility
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Chrome
        uses: browser-actions/setup-chrome@latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm
          cache-dependency-path: test/dummy/package-lock.json

      - name: Install dependencies
        working-directory: test/dummy
        run: npm install

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Prepare the database
        run: bin/rails db:setup

      # - name: Build assets
      #   run: RAILS_GROUPS=assets RAILS_ENV=test bin/rails dartsass:build assets:precompile

      - name: Install foreman
        run: gem install foreman --user-install
        env:
          PATH: ${{ env.PATH }}:$HOME/.gem/ruby/3.2.0/bin

      - name: Start server in the background
        working-directory: test/dummy
        run: bin/dev

      - name: Run accessibility tests
        run: |
          npx pa11y-ci --config .github/workflows/pa11y/wcag2aa.js
